mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('tracker/', include('tracker.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/tracker/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /tracker/
    path('', views.index, name='index'),
    path('entry/new/', views.entry, name='entry_new'),
    path('entry/edit/<int:entry_id>/', views.entry, name='entry_edit'),
]

mysite/polls/models.py
from django.db import models
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/tracker/models.py
from django.db import models
import datetime
from taggit.managers import TaggableManager

# List of tags (e.g. K-On Season 1)
class Tag(models.Model):
    name = models.CharField(max_length=200)
    associated_tags = models.ManyToManyField("self", symmetrical=False)
    def __str__(self):
        for tag in self.associated_tags.all():
            print("Associated tag: ", tag)
        return self.name

class Entry(models.Model):
    date = models.DateField()
    duration = models.IntegerField()
    comment = models.CharField(max_length=280)
    tags = models.ManyToManyField(Tag)
    auto_tags = TaggableManager()
    def __str__(self):
        return_str = ''
        duration_str = 'No duration'
        try:
            date_str = self.date.strftime('%Y-%m-%d')
        except:
            date_str = 'No date'
        try:
            duration_str = str(self.duration)
        except:
            duration_str = 'No duration'
        try:
            comment_str = str(self.comment)
        except:
            comment_str = 'No comment'
        return  (date_str + " for " + duration_str + " minutes\t Comment: " + comment_str)
    @property
    def get_html_url(self):
        url = reverse('entry_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

mysite/tracker/forms.py
from django.forms import ModelForm, DateInput
from tracker.models import Entry, Tag

class EntryForm(ModelForm):
  class Meta:
    model = Entry
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'date': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EntryForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    #datetime.strptime(d, '%b %d %Y %I:%M%p')
    #self.fields['date'].input_formats = ('%Y-%m-%d',)

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/tracker/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Max, Min, Sum
from django.template import loader
from django.urls import reverse
from .models import Entry, Tag
from .forms import EntryForm

import datetime

# Given a date and a Tag id, get the total sum of Entries' durations.
def total_duration(date, tag_id):
    e = Entry.objects.filter(
        tags=Tag.objects.get(pk=tag_id),
        date=date
    ).aggregate(Sum('duration'))
    if(e['duration__sum'] is None):
        return 0
    return e['duration__sum']

# Table view
def index(request):
    template = loader.get_template('index.html')
    date_range = Entry.objects.aggregate(Min('date'), Max('date'))
    date_min = date_range['date__min']
    date_max = date_range['date__max']
    all_dates = [date_min + datetime.timedelta(days=i) for i in range((date_max-date_min).days+2)]
    listening_days = [total_duration(date,1) for date in all_dates]
    reading_days = [total_duration(date,2) for date in all_dates]
    anki_days = [total_duration(date,3) for date in all_dates]
    data = list(zip(all_dates, listening_days, reading_days, anki_days))
    context = {
        'data': data,
    }
    return HttpResponse(template.render(context, request))

def entry(request, entry_id=None):
    instance = Entry()
    if entry_id:
        instance = get_object_or_404(Entry, pk=entry_id)
    else:
        instance = Entry()

    form = EntryForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('index'))
    return render(request, 'entry.html', {'form': form})

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/tracker/templates/entry.html
<!-- cal/templates/cal/event.html -->
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/journal.css' %}">

{% block title %}
Entry
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="/tracker/"> Journal </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

mysite/tracker/templates/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/journal.css' %}">


<div class=container>
  <div class="row">
    <div class="col-md-12 text-white">
      <h1> Immersion Journal </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-bordered table-dark table-hover">
        {% for date, listening, reading, anki in data %}
          <tr>
              <td>{{date}}</td>
              <td>
                <div>{{listening}} min</div>
                <div>{{reading}} min</div>
                <div>{{anki}} min</div>
              </td>
              <td>
                <div>Listening</div>
                <div>Reading</div>
                <div>Anki</div>
              </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
<div>